const filters=document.querySelectorAll('[data-filter]');
const cards=document.querySelectorAll('.project-card');
filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;cards.forEach(c=>c.classList.toggle('hide',f!=='all'&&!c.dataset.cat.split(' ').includes(f)));}));

const menu=document.querySelector('.menu'),nav=document.querySelector('.site-header nav');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));

const studies={
 banking:{tag:'DATA ANALYTICS · DATA ENGINEERING',title:'Personal Banking Customer Analytics',copy:'An end-to-end analytics project focused on organizing and analyzing synthetic personal-banking data across customers, accounts, products, and transactions.',problem:'Create a structured view of customer behavior and turn raw banking data into business-focused insights.',build:'Designed relational data models, wrote SQL analysis queries, and built Python/Pandas workflows for cleaning, transformation, aggregation, and feature engineering.',outcome:'Analyzed customer activity, transaction patterns, product usage, and segments, then translated the results into visual findings and recommendations.',stack:'Python · SQL · PostgreSQL · Pandas · Data Analysis · Feature Engineering'},
 churn:{tag:'MACHINE LEARNING · ANALYTICS',title:'Customer Churn & Retention Analytics',copy:'A customer analytics workflow built to explore the factors associated with churn and retention using structured data, statistics, and machine learning.',problem:'Identify meaningful customer behavior patterns that can help explain churn and support retention decisions.',build:'Performed exploratory analysis, statistical analysis, data preparation, feature engineering, and model-oriented workflow development.',outcome:'Produced visualizations and quantitative findings that connect technical analysis to concise retention-focused recommendations.',stack:'Python · SQL · Statistics · Machine Learning · Data Visualization'},
 studenthub:{tag:'SOFTWARE ENGINEERING',title:'StudentHUB — Real-Time Collaboration',copy:'A university software engineering project developed by a five-person team to support course-based student communication.',problem:'Provide students with persistent, course-based real-time group communication inside a mobile application.',build:'Developed the group-chat feature and supporting PostgreSQL/Supabase data structures, real-time synchronization, persistent retrieval, REST API integration, testing, and debugging.',outcome:'Delivered working group creation and message send/display functionality while coordinating feature integration through Git/GitHub.',stack:'PostgreSQL · Supabase · React Native · TypeScript · Node.js · Express.js · Git'}
};
const dialog=document.querySelector('#case-study'),content=document.querySelector('#case-content');
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{const s=studies[b.dataset.project];content.innerHTML=`<div class="case-tag">${s.tag}</div><h3 class="case-title">${s.title}</h3><p class="case-copy">${s.copy}</p><div class="case-grid"><div><h4>Problem</h4><p>${s.problem}</p></div><div><h4>What I built</h4><p>${s.build}</p></div><div><h4>Outcome</h4><p>${s.outcome}</p></div><div><h4>Stack</h4><p>${s.stack}</p></div></div>`;dialog.showModal();}));
document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});

const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
